### ISSUE TITLE
Styled components overriden when refreshing a page

### ISSUE THREAD

**Issue by zumbuuul** [LiMichael1/Expense-Tracker#6]
Ran into this bug for the first time, i found a github thread that may have a solution

https://github.com/vercel/next.js/issues/4068

If this doesn't help we should find another way to import google fonts.

I imported google fonts with the _document.js file in the pages folder, but that file is causing the problem when the page is refreshed, if we find another way to import google fonts we can delete the `_document.js` file alltogether

**Comment by zumbuuul** [comment]
The bug hasn't been fixed yet... it has really weird behavior

**Comment by LiMichael1** [comment]
https://stackoverflow.com/questions/64740663/next-js-and-styled-components-go-out-of-sync-between-the-server-and-the-client-o

**Comment by LiMichael1** [comment]
Fixed. Check package.json

**Comment by zumbuuul** [comment]
Mike solved the issue by installing a styled components babel plugin
